# Generated by Django 3.2.7 on 2021-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210929_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
